"use client";

import { useState } from "react";
import { Typography } from "@/components/ui/Typography";
import { Button } from "@/components/ui/Button";
import { Play, Sparkles, Wand2, Mic } from "lucide-react";
import { cn } from "@/lib/utils";
import { toast } from "sonner";

interface ScriptInputProps {
    script: string;
    onChange: (val: string) => void;
    voiceId: string | null;
    onVoiceSelect: (id: string) => void;
}

const SAMPLE_SCRIPTS = [
    "Hey guys! I just found the ultimate solution for...",
    "Stop scrolling! If you're looking for better skin...",
    "I can't believe how easy this app makes it to..."
];

export function ScriptInput({ script, onChange, voiceId, onVoiceSelect }: ScriptInputProps) {
    const [isGenerating, setIsGenerating] = useState(false);

    const handleGenerate = () => {
        setIsGenerating(true);
        setTimeout(() => {
            onChange("Hey everyone! Check out this amazing new product that completely changed my daily routine. It's fast, easy, and super effective!");
            setIsGenerating(false);
            toast.success("Script generated by AI!");
        }, 1500);
    };

    return (
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 h-full">
            {/* Left: Input Area */}
            <div className="md:col-span-2 space-y-6">
                <div>
                    <Typography variant="h3" className="mb-1">Write your Script</Typography>
                    <Typography variant="body" className="text-text-2">
                        Type your script below or use AI to generate one.
                    </Typography>
                </div>

                <div className="relative">
                    <textarea
                        value={script}
                        onChange={(e) => onChange(e.target.value)}
                        placeholder="Enter your script here... (e.g. 'Hey guys! Check out this new app...')"
                        className="w-full h-[300px] p-4 bg-bg-2 border border-border-0 rounded-xl resize-none focus:outline-none focus:border-accent transition-colors text-[16px] leading-relaxed"
                    />
                    <div className="absolute bottom-4 right-4 text-[12px] text-text-3 font-medium">
                        {script.length} chars
                    </div>
                </div>

                <div className="flex gap-2">
                    {SAMPLE_SCRIPTS.map((s, i) => (
                        <button
                            key={i}
                            onClick={() => onChange(s)}
                            className="text-[12px] px-3 py-1.5 bg-bg-1 border border-border-0 rounded-lg hover:border-accent/50 transition-colors text-text-2 truncate max-w-[200px]"
                        >
                            &quot;{s}...&quot;
                        </button>
                    ))}
                </div>
            </div>

            {/* Right: AI Tools */}
            <div className="space-y-6">
                <div className="p-6 bg-bg-1 rounded-xl border border-border-0">
                    <div className="flex items-center gap-2 mb-4 text-accent">
                        <Sparkles size={18} />
                        <h4 className="font-bold text-[14px]">AI Assistance</h4>
                    </div>

                    <div className="space-y-3">
                        <Button
                            variant="secondary"
                            className="w-full justify-start gap-2"
                            onClick={handleGenerate}
                            disabled={isGenerating}
                        >
                            <Wand2 size={16} className={isGenerating ? "animate-spin" : ""} />
                            {isGenerating ? "Writing..." : "Generate Magic Script"}
                        </Button>
                        <Button variant="ghost" className="w-full justify-start gap-2">
                            <Mic size={16} />
                            Record Audio
                        </Button>
                    </div>
                </div>

                <div className="p-6 bg-bg-1 rounded-xl border border-border-0">
                    <h4 className="font-bold text-[14px] mb-4">Voice Settings</h4>
                    <div className="space-y-2">
                        {["ElevenLabs - Rachel", "ElevenLabs - Drew", "OpenAI - NOVA"].map((voice) => (
                            <div
                                key={voice}
                                onClick={() => onVoiceSelect(voice)}
                                className={cn(
                                    "flex items-center justify-between p-3 rounded-lg cursor-pointer border transition-all",
                                    voiceId === voice
                                        ? "bg-bg-0 border-accent shadow-sm"
                                        : "bg-bg-2 border-transparent hover:bg-bg-0"
                                )}
                            >
                                <span className="text-[13px] font-medium">{voice}</span>
                                <button className="w-6 h-6 rounded-full bg-bg-2 flex items-center justify-center hover:bg-accent/10 hover:text-accent transition-colors">
                                    <Play size={10} fill="currentColor" />
                                </button>
                            </div>
                        ))}
                    </div>
                </div>
            </div>
        </div>
    );
}
